spring.application.name=MatchX
binance.api.websocket=wss://stream.binance.com:9443/ws/btcusdt@trade

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:matchx}
spring.datasource.username=${DB_USER:matchx}
spring.datasource.password=${DB_PASSWORD:matchx}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
